In [2]:
import cv2
import numpy as np 
import math as mt
import os 
from skimage.measure import compare_ssim
import argparse
import imutils
import scipy.signal as sig
import copy 

In [3]:
mono = cv2.IMREAD_GRAYSCALE
poly = cv2.IMREAD_COLOR
path1 ='./map_from.jpg'

In [9]:
def loading_displaying_saving( path, colour = mono ):
    img = cv2.imread(path, colour)
    cv2.imshow(path, img)
    cv2.waitKey(0)
#     cv2.imwrite('graygirl.jpg', img)

In [6]:
def resizing(img, new_width=None, new_height=None, interp=cv2.INTER_LINEAR):
    h, w = img.shape[:2]
# проверка на наличие изменений
    if new_width is None and new_height is None:
        return img
    else:
# если задана только новая высота.
        if new_width is None:
            ratio = new_height / h
            dimension = (int(w * ratio), new_height)

        else:
            ratio = new_width / w
            dimension = (new_width, int(h * ratio))

        res_img = cv2.resize(img, dimension, interpolation=interp)
        return res_img 

In [5]:
def sampling(img,  size = 2 ):
    if len(img.shape)  == 2:
        new = np.zeros((img.shape[0]//size,img.shape[1]//size))
        print(new.shape)
    if len(img.shape)  == 3:
        new = np.zeros((img.shape[0]//size,img.shape[1]//size, img.shape[3]))
    for i in range(size//2,img.shape[0] - size//2, size): 
        for j in range(size//2,img.shape[1] - size//2, size):
#             for channel in range(img.shape[3]):
            new[ (i-size//2)//size , (j-size//2)//size ] = img[i,j]
    return new
    
    

In [15]:
# sampling test
img  = cv2.imread('./img.jpg', mono) 
img.shape
print(type(img[0,0]))
list(img.shape)
img_blur_3 = cv2.GaussianBlur(img, (3, 3), 0)
print(img_blur_3.shape)
img_blur_3 = sampling(img_blur_3)
print(img_blur_3.shape)
cv2.imwrite('img_blur_3.jpg', img_blur_3)

<class 'numpy.uint8'>
(256, 256)
(128, 128)
(128, 128)


True

In [27]:
# loading_displaying_saving(path1)

Сжатие методом бикубической интерполяции и фильтром ланцеша.

In [10]:
# cv2.INTER_CUBIC
img  = cv2.imread('./map_from.jpg', mono) 
h = img.shape[0]
w = img.shape[1]
koeff  =  2 
print("Before zipping: ", img.shape)
res_img_cubic = resizing(img, new_width = int(w/koeff),interp = cv2.INTER_CUBIC)
res_img_lanz = resizing(img, new_width = int(w/koeff),interp = cv2.INTER_LANCZOS4)
print("After zipping:", res_img_cubic.shape )
# cv2.imshow('res_img', res_img)
cv2.imwrite('res_zip_cubic.jpg', res_img_cubic)
cv2.imwrite('res_zip_lanz.jpg', res_img_lanz)

AttributeError: 'NoneType' object has no attribute 'shape'

Восстановление теми же методами. 

In [11]:
print("Before recovery: ", img.shape)

res_zip_cubic = cv2.imread('./res_zip_cubic.jpg', poly)
res_zip_lanz = cv2.imread('./res_zip_lanz.jpg', poly)

res_rec_cubic = resizing(res_zip_cubic, new_width = w, interp = cv2.INTER_CUBIC)
res_rec_lanz = resizing(res_zip_lanz, new_width = w, interp = cv2.INTER_LANCZOS4)
print("After recovery:", res_img_cubic.shape ) 
# cv2.imshow('res_img', res_img)
cv2.imwrite('res_rec_cubic.jpg', res_rec_cubic)
cv2.imwrite('res_rec_lanz.jpg', res_rec_lanz)

AttributeError: 'NoneType' object has no attribute 'shape'

In [30]:
def gaussian_blurring():
    image = cv2.imread('girl.jpg')
    img_blur_3 = cv2.GaussianBlur(image, (3, 3), 0)
    img_blur_7 = cv2.GaussianBlur(image, (7, 7), 0)
    img_blur_11 = cv2.GaussianBlur(image, (11, 11), 0)

In [44]:
img_blur_3 = cv2.GaussianBlur(img, (3, 3), 0)
img_blur_7 = cv2.GaussianBlur(img, (7, 7), 0)
img_blur_11 = cv2.GaussianBlur(img, (11, 11), 0)

In [31]:
cv2.imwrite('img_blur_3.jpg', img_blur_3)
cv2.imwrite('img_blur_7.jpg', img_blur_7)
cv2.imwrite('img_blur_11.jpg', img_blur_11)

True

In [33]:
type(img_blur_11)

numpy.ndarray

In [34]:
res_INTER_NEAREST = resizing(img_blur_3, new_width = int(w/koeff),interp = cv2.INTER_NEAREST)
cv2.imwrite('res_INTER_NEAREST.jpg', res_INTER_NEAREST) 

True

In [35]:
cv2.PSNR(img, res_rec_cubic)

error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-oduouqig\opencv\modules\core\src\norm.cpp:1096: error: (-215:Assertion failed) _src1.sameSize(_src2) in function 'cv::norm'


In [9]:
def PSNR(img1, img2):
    img1 = img1.astype(np.float64) / 255.
    img2 = img2.astype(np.float64) / 255.
    mse = np.mean((img1 - img2) ** 2)
    if mse == 0:
        return "Same Image"
    return 10 * mt.log10(1. / mse)

# PSNR(img, res_rec_cubic) 

In [ ]:
cv2.SSIM()

In [25]:
# ! pip install SSIM-PIL


"C:\Program" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


In [27]:
# from SSIM_PIL import compare_ssim
# value = compare_ssim(img, img_blur_7)


In [28]:
# ! pip3 install scikit-image opencv-python imutils


  Created wheel for imutils: filename=imutils-0.5.4-py3-none-any.whl size=25860 sha256=7facc28f57861954c40a459be5026f95172630775c4c7ec1eab50f7fcda5997e
  Stored in directory: c:\users\aleksandr\appdata\local\pip\cache\wheels\86\d7\0a\4923351ed1cec5d5e24c1eaf8905567b02a0343b24aa873df2
Successfully built imutils


"C:\Program" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


In [3]:
from skimage.measure import compare_ssim
import argparse
import imutils
import cv2

(score, diff) = compare_ssim(img, res_INTER_NEAREST, full=True, multichannel=True)
diff = (diff * 255).astype("uint8")
score

NameError: name 'img' is not defined

In [4]:
files = os.listdir(path="./pan")  
print(len(files))

257


In [45]:
Loss_cubic_PSNR = []
Loss_lanz_PSNR = []

Loss_cubic_SSIM = []
Loss_lanz_SSIM = []

# Loss_3_PSNR = []
# Loss_7_PSNR = []
# Loss_11_PSNR = []

# Loss_3_SSIM = []
# Loss_7_SSIM = []
# Loss_11_SSIM = []

for file in os.listdir(path="./pan") : 
    path ="./pan"+"/"+file
#     print(path) 

    img  = cv2.imread(path, mono) 
    koeff  =  2 
    w = img.shape[1]
    
    res_img_cubic = resizing(img, new_width = int( w/koeff ),interp = cv2.INTER_CUBIC)
    res_img_lanz = resizing(img, new_width = int( w/koeff ),interp = cv2.INTER_LANCZOS4)
    
    img_blur_3 = cv2.GaussianBlur(img, (3, 3), 0)
    img_blur_7 = cv2.GaussianBlur(img, (7, 7), 0)
    img_blur_11 = cv2.GaussianBlur(img, (11, 11), 0)
    
    res_INTER_NEAREST_3 = resizing(img_blur_3, new_width = int(w/koeff),interp = cv2.INTER_NEAREST)
    res_INTER_NEAREST_7= resizing(img_blur_7, new_width = int(w/koeff),interp = cv2.INTER_NEAREST)
    res_INTER_NEAREST_11 = resizing(img_blur_11, new_width = int(w/koeff),interp = cv2.INTER_NEAREST)

#     Loss_cubic_PSNR.append(cv2.PSNR(img, res_img_cubic))
#     Loss_lanz_PSNR.append(cv2.PSNR(img, res_img_lanz))
    
#     Loss_3_PSNR.append(cv2.PSNR(img, res_INTER_NEAREST_3))
#     Loss_7_PSNR.append(cv2.PSNR(img, res_INTER_NEAREST_7))
#     Loss_11_PSNR.append(cv2.PSNR(img, res_INTER_NEAREST_11))
    
    
#     Loss_cubic_SSIM.append(compare_ssim(img, res_img_cubic, full=True, multichannel=False)[1])
#     Loss_lanz_SSIM.append(compare_ssim(img, res_img_lanz, full=True, multichannel=False)[1])
    
#     Loss_3_SSIM.append(compare_ssim(img, res_INTER_NEAREST_3, full=True, multichannel=False)[1] )
#     Loss_7_SSIM.append(compare_ssim(img, res_INTER_NEAREST_7, full=True, multichannel=False)[1] )
#     Loss_11_SSIM.append(compare_ssim(img, res_INTER_NEAREST_11, full=True, multichannel=False)[1] )
    
    res_rec_cubic = resizing(res_img_cubic, new_width = w, interp = cv2.INTER_CUBIC)
    res_rec_lanz = resizing(res_img_lanz, new_width = w, interp = cv2.INTER_LANCZOS4)
    
    Loss_cubic_PSNR.append(cv2.PSNR(img, res_rec_cubic))
    Loss_lanz_PSNR.append(cv2.PSNR(img, res_rec_lanz))
    
    Loss_cubic_SSIM.append(compare_ssim(img, res_rec_cubic, full=True, multichannel=False)[0])
    Loss_lanz_SSIM.append(compare_ssim(img, res_rec_lanz, full=True, multichannel=False)[0])
    
    (score, diff) = compare_ssim(img, img, full=True, multichannel=False) 
#     diff = (diff * 255).astype("uint8")
#     print(cv2.PSNR(img, img))

print("Cubic PSNR :", sum(Loss_cubic_PSNR) / len(Loss_cubic_PSNR)) 
print("Cubic SSIM :", sum(Loss_cubic_SSIM) / len(Loss_cubic_SSIM))

print("Lanz filter PSNR :",sum(Loss_lanz_PSNR) / len(Loss_lanz_PSNR))
print("Lanz filter SSIM :",sum(Loss_lanz_SSIM) / len(Loss_cubic_SSIM))
    
    

C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:55: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.
C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:56: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.
C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:58: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.


Cubic PSNR : 35.49653662962487
Cubic SSIM : 0.9602639527433899
Lanz filter PSNR : 34.994000264982986
Lanz filter SSIM : 0.953809382850119


In [ ]:
# import cv2
# import numpy as np
# from matplotlib import pyplot as plt
# plt.figure(figsize=(15,12))

# plt.subplot(121)
# plt.imshow(img,cmap = 'gray')
# plt.title('Original Image')

# plt.subplot(122)
# plt.imshow(res,cmap = 'gray')
# plt.title('Downsampled Image')

# plt.show()

## Проект :


In [4]:
def grad( img, i, j): # h w 
    h  = 1
    if img.shape[0] > i + h and 0 <= i - h:
        grad_y = img[ i+h , j]  - img[ i-h, j]
        grad_y /=2
        
    elif img.shape[0] > i + h:
        grad_y = img[ i+h , j]  - img[ i, j]
        
    elif 0 <= i - h : 
        grad_y =  img[ i, j]  - img[ i-h, j]
            
    if img.shape[1] > j + h and 0 <= j - h:
        grad_x = img[ i , j+h]  - img[ i, j-h] 
        grad_x /=2
        
    elif img.shape[1] > j + h:
        grad_x = img[ i , j+h]  - img[ i, j]
        
    elif 0 <= j - h : 
        grad_x =  img[ i, j]  - img[ i, j-h]
        
    return grad_x, grad_y
        


In [6]:
window = 3 
num_ang = window**2 -1 
angle= [ 2*mt.pi/num_ang*i for i in range(num_ang) ]
# angle = np.array(list(map(lambda a :{'cos' : mt.cos(a), 'sin': mt.sin(a)}, angle ))) 
angle = np.array(list(map(lambda a : np.array([mt.cos(a), mt.sin(a)]), angle ))) 
angle.shape

(8, 2)

In [12]:
# img  = cv2.imread('./pan/0002.png', mono) 

img  = cv2.imread('./map_from.jpg', mono) 
print("Origin :",img.shape) 
h = img.shape[0]
w = img.shape[1]
koeff  =  2 
# res_img_cubic = resizing(img, new_width = int(w/koeff),interp = cv2.INTER_CUBIC)
res_img_lanz = resizing(img, new_width = int(w/koeff),interp = cv2.INTER_LANCZOS4)
print()
new = np.zeros((np.array(res_img_lanz.shape)*koeff)) # increase the size to the original
grad_x = np.zeros((np.array(res_img_lanz.shape)*koeff)) 
grad_y = np.zeros((np.array(res_img_lanz.shape)*koeff))
wt = np.empty([res_img_lanz.shape[0]*koeff, res_img_lanz.shape[1]*koeff, window,window ])

w = new.shape[1]
h = new.shape[0]
print("Size of recovered pic :", new.shape)
ind  =  np.indices(new.shape)
# for i, n in enumerate(ind):
#     print(i)
new[::2, ::2] = res_img_lanz  # заполнили опорные значения. 
new1 = new.copy()

for i in range(h):
    for j in range((i+1)&1, w , 2):
        assert new1[i,j] == 0
        if (i+1 < h) and (j+1 < w):
            new1[i,j] = (new[i, j-1] + new[i,j+1])/2*((i+1) & 1) +(new[i-1, j] + new[i+1,j])/2 *((i) & 1) 
        else: 
            new1[i,j] = new[i, j-1] *((i+1) & 1) + new[i-1, j] *((i) & 1) 
for i in range(1, h - 1, 2):
    for j in range (1, w - 1, 2):
#         print(new[i,j])
        grad_x[i, j],  grad_y[i, j] = grad( new1,i,j)
        new_wt = abs(angle @ np.array( [-grad_y[i, j],  grad_x[i, j] ]).reshape((2, 1)) ).reshape(window**2-1,) 
# получим непостредственно маску коэффициентов
        wt[i,j] = np.insert(new_wt, 4 ,  0).reshape((window,window))
#       тогда значение самой ячейки :
        new1[i,j] = ((wt[i,j]*new1[(i-1):(i+2),(j-1):(j+2)]).sum() //(abs(wt[i,j]).sum())).astype(np.uint8)
        new1[i,j] = int(new1[i,j])
         
new1 

Origin : (485, 727)

Size of recovered pic : (484, 726)


C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:40: RuntimeWarning: invalid value encountered in double_scalars


array([[158. , 132. , 106. , ...,  79. ,  79. ,  79. ],
       [165.5, 148. , 137. , ...,  96. ,  98. ,   0. ],
       [173. , 170.5, 168. , ..., 116.5, 117. , 117. ],
       ...,
       [ 27.5,  22. ,  18.5, ..., 122. , 112.5,   0. ],
       [ 28. ,  23. ,  18. , ..., 133.5, 115. , 115. ],
       [ 28. ,   0. ,  18. , ...,   0. , 115. ,   0. ]])

In [26]:
# np.array(res_img_lanz.shape)*2 
a= np.array([[1,2,3,4],[5,6,7,8]])[::2,::2]
a 

array([[1, 3]])

In [121]:
grad_x
type(wt[1,1])#.shape  
i = 1
j = 1
type(new1[(i-1):(i+2),(j-1):(j+2)]) 
print(wt[i,j]*new1[(i-1):(i+2),(j-1):(j+2)])
print(wt[i,j])
print(new1[(i-1):(i+2),(j-1):(j+2)])
(wt[i,j]*new1[(i-1):(i+2),(j-1):(j+2)]).sum()/((wt[i,j]**2).sum()) 



[[  0.         110.48543456 237.5       ]
 [  0.           0.          57.        ]
 [  0.          61.75        59.75052301]]
[[3.         8.83883476 9.5       ]
 [4.59619408 0.         3.        ]
 [8.83883476 9.5        4.59619408]]
[[ 0.  12.5 25. ]
 [ 0.  10.  19. ]
 [ 0.   6.5 13. ]]


1.326161102193102

In [39]:
a =np.array([ i for i in range(25)]).reshape((5, 5))
i = 2
j = 2
print(a[(i-1):(i+2),(j-1):(j+2)])
print(a )

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [73]:
a =np.array([ (-1)**(i)  for i in range(25)]).reshape((5, 5))
abs(a) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
cv2.imwrite('sthNEW.jpg', new1) 
res_rec_cubic = resizing(img, new_width = w, interp = cv2.INTER_CUBIC)
res_rec_lanz = resizing(img, new_width = w, interp = cv2.INTER_LANCZOS4)

In [31]:
# cv2.PSNR(img, new1)
print(type(img[1,1]))  
print(type(new1[1,1])) 
print(img.shape)
print(new1.shape)
print( compare_ssim(img[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ], new1[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ],
             full=True, multichannel=False)[0] )
print( compare_ssim(img[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ], res_rec_cubic[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ],
             full=True, multichannel=False)[0] )
print( compare_ssim(img[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ], res_rec_lanz[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ],
             full=True, multichannel=False)[0] )
print( PSNR(img[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ], new1[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ]))
# print( cv2.PSNR(img[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ], new1[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ]))
print( PSNR(img[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ], res_rec_cubic[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ]))
print( PSNR(img[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ], res_rec_lanz[2:new1.shape[0] - 2, 2:new1.shape[1] - 2 ]))
print( PSNR(img, img)) 
# img.type()

<class 'numpy.uint8'>
<class 'numpy.float64'>
(485, 727)
(484, 726)
0.5643371950066568
0.8042662841935514
0.7998376111303106
21.551952905931373
24.794913601596807
24.693441372549643
Same Image


C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.
  import sys
C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.
  if __name__ == '__main__':
C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: UserWarning: DEPRECATED: skimage.measure.compare_ssim has been moved to skimage.metrics.structural_similarity. It will be removed from skimage.measure in version 0.18.
  # This is added back by InteractiveShellApp.init_path()


In [8]:
b=np.asarray([[1,2,0,1,2],
              [2,3,1,1,2],
              [1,4,2,2,0],
              [3,2,3,3,0],
              [1,0,0,2,1]
              ], dtype=np.float32)

# w=np.asarray([[1,1,1],
#               [1,1,2],
#               [2,1,1]], dtype=np.uint8)

w=np.asarray([[1,0,0],
              [0,0,0],
              [0,0,0]], dtype=np.uint8)

dx = np.asarray([[0,0,0],
                 [-0.5,0,0.5],
                 [0,0,0]], dtype=np.float32)

dy = np.asarray([[0,-0.5,0],
                 [0 , 0, 0],
                 [0 , 0.5,0]], dtype=np.float32)


print(sig.convolve2d(b, dx, mode="same"))
# print("-------")
# print(cv2.filter2D(b, -1, cv2.flip(w, -1), borderType=cv2.BORDER_CONSTANT))
# print("-------")
print(cv2.filter2D(b, -1, dx, borderType=cv2.BORDER_CONSTANT))

[[-1.   0.5  0.5 -1.   0.5]
 [-1.5  0.5  1.  -0.5  0.5]
 [-2.  -0.5  1.   1.   1. ]
 [-1.   0.  -0.5  1.5  1.5]
 [ 0.   0.5 -1.  -0.5  1. ]]
[[ 1.  -0.5 -0.5  1.  -0.5]
 [ 1.5 -0.5 -1.   0.5 -0.5]
 [ 2.   0.5 -1.  -1.  -1. ]
 [ 1.   0.   0.5 -1.5 -1.5]
 [ 0.  -0.5  1.   0.5 -1. ]]


In [11]:
cv2.flip(w, -1)
# 0, for flipping the image around the x-axis (vertical flipping);
# > 0 for flipping around the y-axis (horizontal flipping);
# < 0 for flipping around both axes.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1]], dtype=uint8)

In [9]:
tweight = np.uint8
# Sobel 
dx_s =np.asarray([[-1, -2, -1],
                  [0, 0, 0],
                  [1, 2, 1]], dtype=tweight)

dy_s =np.asarray([[-1, 0, 1],
                  [-2, 0, 2],
                  [-1, 0, 1]], dtype=tweight)

# Previtt
dx_p =np.asarray([[-1, -1, -1],
                  [0, 0, 0],
                  [1, 1, 1]], dtype=tweight)

dy_p =np.asarray([[-1, 0, 1],
                  [-1, 0, 1],
                  [-1, 0, 1]], dtype=tweight)
# sharra
dx_sh =np.asarray([[+3, 10, 3],
                  [0, 0, 0],
                  [-3, 10, -3]], dtype=tweight)

dy_sh =np.asarray([[3, 0, -3],
                  [10, 0, -10],
                  [3, 0, -3]], dtype=tweight)


In [15]:
# img  = cv2.imread('./map_from.jpg', mono) 
# 0 - черный,255 - белый.
img  = cv2.imread('./pan/0002.png', mono)
img.shape
type(img)
img_weight_x = cv2.filter2D(img, -1, dx_sh, borderType=cv2.BORDER_CONSTANT)
img_weight_y = cv2.filter2D(img, -1, dy_sh,  borderType=cv2.BORDER_CONSTANT)
img_weight =  (img_weight_x**2+img_weight_y**2)**0.5
cv2.imwrite('img_weight.jpg', img_weight)
cv2.imwrite('img_weight_x.jpg', img_weight_x)
cv2.imwrite('img_weight_y.jpg', img_weight_y)
zeros = np.ones_like( img_weight_x )*255
cv2.imwrite('zeros.jpg', zeros )
img_weight  = np.array((np.array(img_weight_x, dtype = np.uint16)**2+np.array(img_weight_y, dtype = np.uint16)**2)**0.5, dtype = np.uint8)
c


253


True

In [16]:
def recover(img, w = 512, h = 512, num_angles = 4, flter  = dx_sh ):
    new = np.zeros((h,w)) # increase the size to the original
    new_x = np.copy(new)
    new_y = np.copy(new)
    new_o = np.zeros_like(img)
    conv =np.asarray([[0, 0, 0],
                  [0, 0.25, 0.25],
                  [0, 0.25, 0.25]], dtype=np.float32)
    
    img_weight_x = cv2.filter2D(img, -1, flter, borderType=cv2.BORDER_CONSTANT)
    img_weight_y = cv2.filter2D(img, -1, flter,  borderType=cv2.BORDER_CONSTANT)
# будем считать, что градиент в цетральной точке o равен 1/4( sum градинетов в ближайших точках)
    grad_x = cv2.filter2D(img_weight_x, -1, conv, borderType=cv2.BORDER_CONSTANT)
    grad_y = cv2.filter2D(img_weight_y, -1, conv, borderType=cv2.BORDER_CONSTANT)

    angle= [ 2*mt.pi/num_angles*i for i in range(num_angles) ]
    # angle = np.array(list(map(lambda a :{'cos' : mt.cos(a), 'sin': mt.sin(a)}, angle ))) 
    angle = np.array(list(map(lambda a : np.array([mt.cos(a), mt.sin(a)]), angle ))) 
#     wt = np.zeros((num_angles, h, w))
    wt = np.array(list(map(lambda a:  abs(- a[0]*grad_y + a[1]*grad_x), angle )))
    print(wt.shape)
#     ВИНМАТЕЛЬНО С РАЗМЕРОМ МАТРИЦЫ ВЕСОВ, она здесь статична 
    Wt = np.array([np.asarray( i.reshape((2,2)), dtype = np.float32)  for i in wt.reshape(num_angles,wt.shape[1]*wt.shape[2]).transpose(1,0)]).reshape((wt.shape[1],wt.shape[2],2,2))
    for i in range(new_o.shape[0] - 1):
        for j in range (new_o.shape[1] - 1 ):
#             new_o[i,j] = (img[i:i+2,j:j+2] * Wt[i,j]).sum()  // ( (Wt[i,j]**2).sum())**0.5
            o = (img[i:i+2,j:j+2] * Wt[i,j]).sum()  // ( (Wt[i,j]**2).sum())**0.5
            if np.isnan(o): 
#                 print("Числитель :", (img[i:i+2,j:j+2] * Wt[i,j]).sum())
#                 print("Знаменатель :",( Wt[i,j]))
                new_o[i,j] = np.mean(img[i:i+2,j:j+2])
#                 img[i,j] = 255
            else:
                new_o[i,j] = o

    img_weight_x_o = cv2.filter2D(new_o, -1, flter, borderType=cv2.BORDER_CONSTANT)
    img_weight_y_o = cv2.filter2D(new_o, -1, flter,  borderType=cv2.BORDER_CONSTANT)
    
    conx =np.asarray([[0, 0.25, 0],
                  [0.25, 0, 0.25],
                  [0, 0.25, 0]], dtype=np.float32)

    for i in range(h):
        for j in range( i & 1 , w, 2):
            new[i, j] = (i & 1)*new_o[ i//2, j//2] + ( (i+1) & 1)*img[i//2, j//2]
            new_x[i, j] = (i & 1)*img_weight_x_o[ i//2, j//2] + ( (i+1) & 1)*img_weight_x[i//2, j//2]
            new_y[i, j] =(i & 1)*img_weight_y_o[ i//2, j//2] + ( (i+1) & 1)*img_weight_y[i//2, j//2]
            
    print(type(new_x))
    print(type(new_y))
            
    grad_x = cv2.filter2D(new_x, -1, conx, borderType=cv2.BORDER_CONSTANT)
    grad_y = cv2.filter2D(new_y, -1, conx, borderType=cv2.BORDER_CONSTANT)
    
    num_angles_x  = 4 
    angle_x = [ 2*mt.pi/num_angles*i for i in range(num_angles_x) ]
    angle_x = np.array(list(map(lambda a : np.array([mt.cos(a), mt.sin(a)]), angle_x )))
#     num_angles * h *w
    wt = np.array(list(map(lambda a:  abs(- a[0]*grad_y + a[1]*grad_x), angle_x )))
    print(wt.shape)
    for i in range(h-1):
        for j in range(((i+1) & 1 ), w-1, 2 ):
            for k in range(num_angles_x):
                participating = np.array([new[i,j+1],new[i-1,j], new[i,j-1], new[i+1,j]])
                weight = wt[:, i, j]
                new[i,j] = np.sum(weight*participating)// ((weight**2).sum())
# 
#                 new[i,j] = 
              
            
    
#     avconv =np.asarray([[0, 0.25, 0],
#                   [0.25, 0, 0.25],
#                   [0, 0.25, 0]], dtype=np.float32)
    
#     new = cv2.filter2D(new, -1, avconv, borderType=cv2.BORDER_CONSTANT)
    cv2.imwrite("new.jpg", new)
    
                

#             print(( (Wt[i,j]**2).sum())**0.5)

koeff = 2    
img = cv2.imread('./pan/0002.png', mono)
img_lanz = resizing(img, new_width = int(img.shape[1]/koeff),interp = cv2.INTER_LANCZOS4)
recover(img_lanz)
# print(img.shape )


(4, 256, 256)


C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: RuntimeWarning: invalid value encountered in floor_divide


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(4, 512, 512)


C:\Users\Aleksandr\Anaconda3\lib\site-packages\ipykernel_launcher.py:66: RuntimeWarning: invalid value encountered in double_scalars


In [ ]:
import cv2
import numpy as np 
import math as mt
import os 
from skimage.measure import compare_ssim
import argparse
import imutils
import scipy.signal as sig

In [ ]:
mono = cv2.IMREAD_GRAYSCALE
poly = cv2.IMREAD_COLOR
path1 ='./pan/

## Скачаем изображения в высоком качестве : 


In [24]:
img = np.zeros((len(os.listdir(path="./pan") ), 512, 512))
i = 0
for file in os.listdir(path="./pan") : 
    path ="./pan"+"/"+file
    img[i,:,:] = cv2.imread(path, mono) 
    i+=1 
img.shape

(257, 512, 512)

 # Создадим размытую тестовую выборку :

In [8]:
# функция загрузки и показа изображения. 
def loading_displaying_saving( path, colour = mono ):
    img = cv2.imread(path, colour)
    cv2.imshow(path, img)
    cv2.waitKey(0)

    
#уменьшение  размера некоторым интервалам 
def resizing(img, new_width=None, new_height=None, interp=cv2.INTER_LINEAR):
    h, w = img.shape[:2]
# проверка на наличие изменений
    if new_width is None and new_height is None:
        return img
    else:
# если задана только новая высота.
        if new_width is None:
            ratio = new_height / h
            dimension = (int(w * ratio), new_height)

        else:
            ratio = new_width / w
            dimension = (new_width, int(h * ratio))

        res_img = cv2.resize(img, dimension, interpolation=interp)
        return res_img 

def sampling(img,  size = 2 ):
    if len(img.shape)  == 2:
        new = np.zeros((img.shape[0]//size,img.shape[1]//size))
#         print(new.shape)
    if len(img.shape)  == 3:
        new = np.zeros((img.shape[0]//size,img.shape[1]//size, img.shape[3]))
    for i in range(size//2,img.shape[0] - size//2, size): 
        for j in range(size//2,img.shape[1] - size//2, size):
#             for channel in range(img.shape[3]):
            new[ (i-size//2)//size , (j-size//2)//size ] = img[i,j]
    return new
    

In [11]:
for file in os.listdir(path="./pan") : 
    path ="./pan"+"/"+file
#     print(path) 
    img  = cv2.imread(path, mono) 
    koeff  =  2 
    w = img.shape[1]
    img = sampling(cv2.GaussianBlur(img, (3, 3), 0), 2 )
    cv2.imwrite("./blurImg/{}".format(file), img)
    

    


In [11]:
5 & 1

1